### ISSUE TITLE
Making trained model available?

### ISSUE THREAD

**Issue by erickrf** [zackthoutt/got-book-6#13]
Nice project!
Is there any chance you could provide the trained model, so we can play a bit with it without going through the trouble of training a new one from scratch?

**Comment by zackthoutt** [comment]
Unfortunately I trained the model back in June on Floydhub. When I initially shared the project there wasn't much interest, so I deleted the Floydhub projects since it costs money to store data. It wasn't until almost a month later that the project's popularity took off.

I'm working on an upgraded version 2 right now though and I'll make sure to upload the full trained model for that when I'm done.
